using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.AI;


namespace RPG.SceneManagment
{
  public class Portal : MonoBehaviour
  {
    [SerializeField] int sceneToLoad = -1;
    [SerializeField] Transform spawnPoint;


    void OnTriggerEnter(Collider other)
    {
      if (other.CompareTag("Player"))
      {
        StartCoroutine(Transition());
      }

    }

    private IEnumerator Transition()
    {
      DontDestroyOnLoad(gameObject);
      yield return SceneManager.LoadSceneAsync(sceneToLoad);

      Portal otherPortal = GetOtherPortal();
      UpdatePlayer(otherPortal);

      Destroy(gameObject);
    }

    private void UpdatePlayer(Portal otherPortal)
    {
      GameObject player = GameObject.FindWithTag("Player");
      player.GetComponent<NavMeshAgent>().Warp(otherPortal.spawnPoint.position);
      player.transform.rotation = otherPortal.spawnPoint.rotation;
    }

    private Portal GetOtherPortal()
    {

      foreach (Portal portal in FindObjectsOfType<Portal>())
      {
        if (portal == this) continue;
        return portal;
      }
      return null;
    }
  }
}
